[project]
name = "platform-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "parquet-tools>=0.2.16",
    "pyarrow>=24.0.0",
    "bctrealtimesdk-subscriber",
    "altair>=6.2.2",
    "vl-convert-python>=1.9.0.post1",
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "protobuf>=4.23.4",
    "pydantic>=2.13.4",
]
[tool.uv.sources]
bctrealtimesdk-subscriber = { path = "./lib/bctRealtimeSDK_Subscriber-3.1.0-py3-none-any.whl" }
